2020-07-22 09:40:58,230 INFO 36372 [egg:logger] init all loggers with options: {"dir":"/Users/yqg/personal/projects/nsc-service/logs/nsc-service","encoding":"utf8","env":"local","level":"INFO","consoleLevel":"INFO","disableConsoleAfterReady":false,"outputJSON":false,"buffer":true,"appLogName":"nsc-service-web.log","coreLogName":"egg-web.log","agentLogName":"egg-agent.log","errorLogName":"common-error.log","coreLogger":{"consoleLevel":"WARN"},"allowDebugAtProd":false,"type":"agent"}
2020-07-22 09:40:58,238 INFO 36372 [egg:core] dump config after load, 4ms
2020-07-22 09:40:58,276 INFO 36372 [egg-watcher] Start watching: ["/Users/yqg/personal/projects/nsc-service/app","/Users/yqg/personal/projects/nsc-service/config","/Users/yqg/personal/projects/nsc-service/mocks","/Users/yqg/personal/projects/nsc-service/mocks_proxy","/Users/yqg/personal/projects/nsc-service/app.js"]
2020-07-22 09:40:58,276 INFO 36372 [egg-watcher] Start watching: "/Users/yqg/personal/projects/nsc-service/app"
2020-07-22 09:40:58,277 INFO 36372 [egg-watcher] Start watching: "/Users/yqg/personal/projects/nsc-service/config"
2020-07-22 09:40:58,277 INFO 36372 [egg-watcher] Start watching: "/Users/yqg/personal/projects/nsc-service/mocks"
2020-07-22 09:40:58,277 INFO 36372 [egg-watcher] Start watching: "/Users/yqg/personal/projects/nsc-service/mocks_proxy"
2020-07-22 09:40:58,277 INFO 36372 [egg-watcher] Start watching: "/Users/yqg/personal/projects/nsc-service/app.js"
2020-07-22 09:40:58,277 INFO 36372 [egg-watcher:agent] watcher start success
2020-07-22 09:40:58,302 INFO 36372 [egg:core] dump config after ready, 17ms
2020-07-22 09:40:58,835 INFO 36372 [egg-watcher] Received a change event from eventSource: {"event":"rename","path":"/Users/yqg/personal/projects/nsc-service/app/public","stat":{"dev":16777220,"mode":16877,"nlink":2,"uid":501,"gid":20,"rdev":0,"blksize":4096,"ino":23623707,"size":64,"blocks":0,"atimeMs":1595382058823.2708,"mtimeMs":1595382058823.2708,"ctimeMs":1595382058823.2708,"birthtimeMs":1595382058823.2708,"atime":"2020-07-22T01:40:58.823Z","mtime":"2020-07-22T01:40:58.823Z","ctime":"2020-07-22T01:40:58.823Z","birthtime":"2020-07-22T01:40:58.823Z"},"remove":false,"isDirectory":true,"isFile":false}
2020-07-22 10:43:06,961 ERROR 36372 nodejs.ClusterClientNoResponseError: client no response in 2947965ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/yqg/personal/projects/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 36372
hostname: yqgdeMBP-10.lan

2020-07-22 19:04:47,904 ERROR 36372 nodejs.ClusterClientNoResponseError: client no response in 2273927ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/yqg/personal/projects/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 36372
hostname: yqgdeMBP-10.lan

2020-07-22 19:42:50,182 ERROR 36372 nodejs.ClusterClientNoResponseError: client no response in 2260794ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/yqg/personal/projects/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 36372
hostname: yqgdeMBP-10.lan

2020-07-23 02:08:48,793 ERROR 36372 nodejs.ClusterClientNoResponseError: client no response in 14417697ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/yqg/personal/projects/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 36372
hostname: yqgdeMBP-10.lan

2020-07-23 04:09:02,188 ERROR 36372 nodejs.ClusterClientNoResponseError: client no response in 7213230ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/yqg/personal/projects/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 36372
hostname: yqgdeMBP-10.lan

2020-07-23 06:09:23,076 ERROR 36372 nodejs.ClusterClientNoResponseError: client no response in 7220314ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/yqg/personal/projects/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 36372
hostname: yqgdeMBP-10.lan

2020-07-23 06:22:45,011 ERROR 36372 nodejs.ClusterClientNoResponseError: client no response in 801439ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/yqg/personal/projects/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 36372
hostname: yqgdeMBP-10.lan

2020-07-23 07:16:06,155 ERROR 36372 nodejs.ClusterClientNoResponseError: client no response in 3178749ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/yqg/personal/projects/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 36372
hostname: yqgdeMBP-10.lan

2020-07-23 08:26:05,773 ERROR 36372 nodejs.ClusterClientNoResponseError: client no response in 3858241ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/yqg/personal/projects/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 36372
hostname: yqgdeMBP-10.lan

2020-07-23 10:42:27,091 ERROR 36372 nodejs.ClusterClientNoResponseError: client no response in 3699610ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/yqg/personal/projects/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 36372
hostname: yqgdeMBP-10.lan

